language: cpp
compiler:
  - gcc
  - clang
git:
  submodules: false
cache: apt
before_install:
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository -y ppa:roblib/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y scons libglew-dev libsdl2-dev libsdl2-image-dev
  - sudo apt-get install -qq -y libbullet-dev libvorbis-dev libcurl4-gnutls-dev
script:
  - scons
branches:
  only:
    - master
	- vertex
notifications:
  email:
    recipients:
      - core13@gmx.net
    on_success: change
    on_failure: always
